# Generated by Django 3.0.7 on 2020-06-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bokkmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_mane', models.CharField(max_length=50)),
                ('site_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
