# Generated by Django 3.0.7 on 2020-06-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bokkmark',
            new_name='Bookmark',
        ),
    ]
