# Generated by Django 3.0.7 on 2020-06-13 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200613_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='site_mane',
            new_name='site_name',
        ),
    ]
